spring:
  h2:
    console:
      enabled: true

  # H2
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:~/order2;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password:

  # MySQL
  datasource:
    url: jdbc:mysql://localhost/test_schema
    username: root
    password: root1234

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create  # create or validate
    show-sql: true
    properties:
      hibernate.format_sql: true