#spring:
#  datasource:
#    url: jdbc:mysql://localhost/test_schema
#    username: root
#    password: root1234
#
#  jpa:
#    open-in-view: false
#    hibernate:
#      ddl-auto: create  # create or validate
#    show-sql: true
#    properties:
#      hibernate.format_sql: true