spring:
  profiles:
    include:
      - domain

server:
  port: 8082
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true




#spring:
#  # MySQL
#  datasource:
#    url: jdbc:mysql://localhost/dummy_schema
#    username: root
#    password: root1234
#
#  jpa:
#    open-in-view: false
#    hibernate:
#      ddl-auto: create  # create or validate
#    show-sql: true
#    properties:
#      hibernate.format_sql: true