server:
  port: 8082
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

#spring:
#  config:
#    import: classpath:application-domain.yaml
#
#spring:
#  profiles:
#    include: domain




spring:
  # MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/dummy_schema
    username: root
    password: root1234

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create  # create or validate
    show-sql: true
    properties:
      hibernate.format_sql: true